import { Artikel, GaleriFoto, Pengurus, Prestasi } from '@/types'

export const articles: Artikel[] = [
  {
    id: '1',
    title: 'Darul Arqam Dasar (DAD) 2026',
    slug: 'darul-arqam-dasar-2026',
    category: 'Kegiatan',
    author: 'IMMawati Anna',
    published_at: '2026-03-15',
    content: '<p>Pintu gerbang pertama bagi mahasiswa untuk mengenal dan bergabung dengan keluarga besar IMM Siti Munjiyah.</p>',
    status: 'published',
    created_at: '2026-03-10',
    images: [],
  },
  {
    id: '2',
    title: 'Munjiyah Literacy Club Vol. 12',
    slug: 'munjiyah-literacy-club-vol-12',
    category: 'Intelektual',
    author: 'IMMawati Eldina',
    published_at: '2026-03-08',
    content: '<p>Diskusi rutin mingguan membedah isu terkini dan karya ilmiah dari berbagai perspektif pendidikan.</p>',
    status: 'published',
    created_at: '2026-03-05',
    images: [],
  },
  {
    id: '3',
    title: 'Siti Munjiyah Berbagi Ramadan',
    slug: 'siti-munjiyah-berbagi-ramadan',
    category: 'Sosial',
    author: 'IMMawati Fatimah',
    published_at: '2026-02-22',
    content: '<p>Gerakan nyata pengabdian masyarakat dengan berbagi takjil dan santunan anak yatim.</p>',
    status: 'published',
    created_at: '2026-02-20',
    images: [],
  },
  {
    id: '4',
    title: 'Lolos PKM-PM Kemendikbudristek 2025',
    slug: 'lolos-pkm-pm-kemendikbudristek-2025',
    category: 'Prestasi',
    author: 'IMMawati Alifah',
    published_at: '2026-02-10',
    content: '<p>Tim PKM-PM IMM Siti Munjiyah berhasil lolos pendanaan Kementerian Pendidikan dan Kebudayaan.</p>',
    status: 'published',
    created_at: '2026-02-08',
    images: [],
  },
  {
    id: '5',
    title: 'Pelatihan Kader Lanjut (PKL) 2026',
    slug: 'pelatihan-kader-lanjut-2026',
    category: 'Kaderisasi',
    author: 'IMMawati Lisa',
    published_at: '2026-01-25',
    content: '<p>Program pengkaderan lanjutan bagi kader yang telah menyelesaikan DAD.</p>',
    status: 'published',
    created_at: '2026-01-20',
    images: [],
  },
  {
    id: '6',
    title: 'Juara 1 International Essay Competition ALIEC 2025',
    slug: 'juara-1-aliec-2025',
    category: 'Prestasi',
    author: 'IMMawati Dini',
    published_at: '2026-01-15',
    content: '<p>IMMawati Dini Nur Azizah berhasil meraih juara 1 dalam ajang internasional.</p>',
    status: 'published',
    created_at: '2026-01-10',
    images: [],
  },
]

export const galeri: GaleriFoto[] = [
  { id: '1', image_url: '', caption: 'DAD 2025', category: 'Kaderisasi', event_date: '2025-10-15', created_at: '2025-10-16' },
  { id: '2', image_url: '', caption: 'MLC Vol. 10', category: 'Intelektual', event_date: '2025-09-20', created_at: '2025-09-21' },
  { id: '3', image_url: '', caption: 'Berbagi Ramadan', category: 'Sosial', event_date: '2025-03-10', created_at: '2025-03-11' },
  { id: '4', image_url: '', caption: 'PIMPTA 2025', category: 'Kegiatan', event_date: '2025-08-05', created_at: '2025-08-06' },
  { id: '5', image_url: '', caption: 'PKL 2026', category: 'Kaderisasi', event_date: '2026-01-25', created_at: '2026-01-26' },
  { id: '6', image_url: '', caption: 'ALIEC 2025', category: 'Prestasi', event_date: '2025-12-15', created_at: '2025-12-16' },
  { id: '7', image_url: '', caption: 'P2MW', category: 'Prestasi', event_date: '2025-11-01', created_at: '2025-11-02' },
  { id: '8', image_url: '', caption: 'Porsema 2025', category: 'Kegiatan', event_date: '2025-07-20', created_at: '2025-07-21' },
]

export const pengurus: Pengurus[] = [
  { id: '1', name: 'IMMawan Faris', position: 'Ketua Umum', group: 'pimpinan', unit_name: '', photo_url: '', period: '2025/2026', order: 1 },
  { id: '2', name: 'IMMawati Anna', position: 'Sekretaris Umum', group: 'pimpinan', unit_name: '', photo_url: '', period: '2025/2026', order: 2 },
  { id: '3', name: 'IMMawati Ayu', position: 'Bendahara Umum', group: 'pimpinan', unit_name: '', photo_url: '', period: '2025/2026', order: 3 },
  { id: '4', name: 'IMMawati Salma', position: 'Bendahara Umum', group: 'pimpinan', unit_name: '', photo_url: '', period: '2025/2026', order: 4 },
  // Bidang Organisasi
  { id: '5', name: 'IMMawati Deswita', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang Organisasi', photo_url: '', period: '2025/2026', order: 5 },
  { id: '101', name: 'IMMawati Salwa', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang Organisasi', photo_url: '', period: '2025/2026', order: 6 },
  { id: '102', name: 'IMMawati Muna', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Organisasi', photo_url: '', period: '2025/2026', order: 7 },
  { id: '103', name: 'IMMawati Aurel', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Organisasi', photo_url: '', period: '2025/2026', order: 8 },
  { id: '104', name: 'IMMawati Aisyah', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Organisasi', photo_url: '', period: '2025/2026', order: 9 },
  { id: '105', name: 'IMMawati Meiva', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Organisasi', photo_url: '', period: '2025/2026', order: 10 },
  { id: '106', name: 'IMMawati Eva', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Organisasi', photo_url: '', period: '2025/2026', order: 11 },
  // Bidang Kader
  { id: '6', name: 'IMMawati Lisa', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang Kader', photo_url: '', period: '2025/2026', order: 12 },
  { id: '107', name: 'IMMawati Nabila', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang Kader', photo_url: '', period: '2025/2026', order: 13 },
  { id: '108', name: 'IMMawan Nauval', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Kader', photo_url: '', period: '2025/2026', order: 14 },
  // Bidang HPKP
  { id: '7', name: 'IMMawati Dwi Rahma', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang HPKP', photo_url: '', period: '2025/2026', order: 15 },
  { id: '109', name: 'IMMawati Nabila H', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang HPKP', photo_url: '', period: '2025/2026', order: 16 },
  { id: '110', name: 'IMMawati Alifah', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang HPKP', photo_url: '', period: '2025/2026', order: 17 },
  { id: '111', name: 'IMMawati Leni', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang HPKP', photo_url: '', period: '2025/2026', order: 18 },
  { id: '112', name: 'IMMawati Warda', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang HPKP', photo_url: '', period: '2025/2026', order: 19 },
  // Bidang RPK
  { id: '8', name: 'IMMawati Fawaz', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang RPK', photo_url: '', period: '2025/2026', order: 20 },
  { id: '113', name: 'IMMawati Nabela', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang RPK', photo_url: '', period: '2025/2026', order: 21 },
  { id: '114', name: 'IMMawan Attar', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang RPK', photo_url: '', period: '2025/2026', order: 22 },
  { id: '115', name: 'IMMawati Faza', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang RPK', photo_url: '', period: '2025/2026', order: 23 },
  { id: '116', name: 'IMMawati Salma', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang RPK', photo_url: '', period: '2025/2026', order: 24 },
  // Bidang SPM
  { id: '9', name: 'IMMawati Fatimah', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang SPM', photo_url: '', period: '2025/2026', order: 25 },
  { id: '117', name: 'IMMawati Nurul', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang SPM', photo_url: '', period: '2025/2026', order: 26 },
  { id: '118', name: 'IMMawati Ariqah', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang SPM', photo_url: '', period: '2025/2026', order: 27 },
  { id: '119', name: 'IMMawati Zaskia', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang SPM', photo_url: '', period: '2025/2026', order: 28 },
  { id: '120', name: 'IMMawati Humairah', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang SPM', photo_url: '', period: '2025/2026', order: 29 },
  // Bidang IMMawati
  { id: '10', name: 'IMMawati Novi', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang IMMawati', photo_url: '', period: '2025/2026', order: 30 },
  { id: '121', name: 'IMMawati Kholif', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang IMMawati', photo_url: '', period: '2025/2026', order: 31 },
  { id: '122', name: 'IMMawan Febri', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang IMMawati', photo_url: '', period: '2025/2026', order: 32 },
  { id: '123', name: 'IMMawati Rosita', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang IMMawati', photo_url: '', period: '2025/2026', order: 33 },
  // Bidang TKK
  { id: '11', name: 'IMMawan Rizki', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang TKK', photo_url: '', period: '2025/2026', order: 34 },
  { id: '124', name: 'IMMawati Kindi', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang TKK', photo_url: '', period: '2025/2026', order: 35 },
  { id: '125', name: 'IMMawati Najwa', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang TKK', photo_url: '', period: '2025/2026', order: 36 },
  { id: '126', name: 'IMMawan Marvel', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang TKK', photo_url: '', period: '2025/2026', order: 37 },
  { id: '127', name: 'IMMawan Fadly', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang TKK', photo_url: '', period: '2025/2026', order: 38 },
  // Bidang Medkom
  { id: '12', name: 'IMMawati Eldina', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang Medkom', photo_url: '', period: '2025/2026', order: 39 },
  { id: '128', name: 'IMMawati Irsyada', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang Medkom', photo_url: '', period: '2025/2026', order: 40 },
  { id: '129', name: 'IMMawati Hanin', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Medkom', photo_url: '', period: '2025/2026', order: 41 },
  { id: '130', name: 'IMMawan Firdaus', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Medkom', photo_url: '', period: '2025/2026', order: 42 },
  { id: '131', name: 'IMMawan Kholik', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang Medkom', photo_url: '', period: '2025/2026', order: 43 },
  // Bidang SBO
  { id: '13', name: 'IMMawati Tora', position: 'Ketua Bidang', group: 'bidang', unit_name: 'Bidang SBO', photo_url: '', period: '2025/2026', order: 44 },
  { id: '132', name: 'IMMawati Anggita', position: 'Sekretaris Bidang', group: 'bidang', unit_name: 'Bidang SBO', photo_url: '', period: '2025/2026', order: 45 },
  { id: '133', name: 'IMMawati Dini', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang SBO', photo_url: '', period: '2025/2026', order: 46 },
  { id: '134', name: 'IMMawati Ica', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang SBO', photo_url: '', period: '2025/2026', order: 47 },
  { id: '135', name: 'IMMawati Sherly', position: 'Anggota Bidang', group: 'bidang', unit_name: 'Bidang SBO', photo_url: '', period: '2025/2026', order: 48 },
  // Unit Pembantu Pimpinan
  { id: '14', name: 'IMMawati Widi', position: 'Ketua Unit', group: 'unit', unit_name: 'LO BUMK', photo_url: '', period: '2025/2026', order: 49 },
  { id: '15', name: 'IMMawati Damar', position: 'Ketua Unit', group: 'unit', unit_name: 'LSO PUSAKA', photo_url: '', period: '2025/2026', order: 50 },
  { id: '16', name: 'IMMawati Alifia', position: 'Ketua Unit', group: 'unit', unit_name: 'LSO LENTERA', photo_url: '', period: '2025/2026', order: 51 },
  { id: '17', name: 'IMMawati Bunga', position: 'Ketua Unit', group: 'unit', unit_name: 'LSO IMD', photo_url: '', period: '2025/2026', order: 52 },
  { id: '18', name: 'IMMawati Rani', position: 'Ketua Unit', group: 'unit', unit_name: 'LSO GARDA', photo_url: '', period: '2025/2026', order: 53 },
]

export const prestasi: Prestasi[] = [
  { id: '1', title: 'Gold B Medal Folklore & Mixed Choir', description: '3rd Soegijapranata International Choir Competition', order: 1 },
  { id: '2', title: 'Lolos Pendanaan P2MW Kemendikbud', description: 'Deswita, Fatimah, Bilqis, Ariqah', order: 2 },
  { id: '3', title: 'Lolos Pendanaan PKM-PM 2024 Kemendikbudristek', description: 'Alifah, Salma, Ja\'anur', order: 3 },
  { id: '4', title: 'Juara 1 International Essay Competition ALIEC 2025', description: 'IMMawati Dini Nur Azizah', order: 4 },
  { id: '5', title: 'Juara 3 Lomba Tahfidz Juz 30 HMP PGSD UMS', description: 'IMMawati Najwa', order: 5 },
  { id: '6', title: 'Juara 2 Lomba Konten Islami HMP PGSD UMS', description: 'IMMawati Meiva & Dhika', order: 6 },
  { id: '7', title: 'Juara 1 Lomba Poster Digital HMP PBSI UMS', description: 'IMMawati Eldina', order: 7 },
  { id: '8', title: 'Juara 2 Kelas C Putra Kejuaraan Antar Fakultas 2025', description: 'IMMawan Nauval', order: 8 },
  { id: '9', title: 'Juara 2 Kelas Under A Putri Kejuaraan Antar Fakultas 2025', description: 'IMMawati Tiara', order: 9 },
  { id: '10', title: 'Harapan 3 PIMPTA Muhammadiyah Nasional ke-4', description: 'Eva Yulianti', order: 10 },
  { id: '11', title: 'Juara 1 Lomba Poster Porsema 2025', description: 'IMMawati Nindy', order: 11 },
]
